added run migration logic

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -211,8 +211,168 @@ jobs:
           # Here's where you will add some code to rollback on failure 
       - destroy-environment:
           id: ${CIRCLE_WORKFLOW_ID:0:7}
-          cond: on_fail                   
+          cond: on_fail  
   
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+      # Docker image here that supports NodeJS
+    steps:
+      # Checkout code from git
+      - checkout
+      # restore the backend cache
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          # Your code here
+          # Run and save the migration output
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+          # exit 1
+      - run:
+          name: Send migration results to memstash
+          # Your code here
+          command: |
+            cd backend
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" \
+              --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            fi
+          # exit 1       
+      # Here's where you will add some code to rollback on failure   
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+          cond: on_fail 
+
+  deploy-frontend:
+    # Docker image here that supports AWS CLI
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies - Python
+          # your code here  -> Refer to https://docs.aws.amazon.com/cli/v1/userguide/install-linux.html
+          command: |
+            cd frontend
+            sudo apt-get update
+            sudo apt-get install python    
+      - run: python --version
+      - run:
+          name: Install dependencies - AWSCLI
+          # your code here  -> Refer to https://docs.aws.amazon.com/cli/v1/userguide/install-linux.html
+          command: |
+            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+            unzip awscli-bundle.zip
+            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+      
+      - run:
+          name: Install dependencies - NPM
+          # your code here  -> https://docs.npmjs.com/cli/v6/commands/npm-install
+          command: |
+            cd frontend
+            sudo npm install
+      - run:
+          name: Install dependencies - Nodejs
+          # your code here  -> Refer to https://docs.aws.amazon.com/cli/v1/userguide/install-linux.html
+          command: |
+            cd frontend
+            sudo apt install nodejs
+      - run:
+          name: Get backend url
+          # your code here - Copied ec2 describe code from Deploy Infrastructure!
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text)
+  
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          # your code here
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      
+      # Here's where you will add some code to rollback on failure 
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+          cond: on_fail
+
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible 
+      # It should have Python for Woking as Control Node. Refer https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-node-requirements
+      - image: cimg/python:3.10.0
+    steps:
+      # Checkout code from git
+      - checkout
+      # Add ssh keys with fingerprint  --> https://circleci.com/docs/2.0/add-ssh-key/#adding-ssh-keys-to-a-job
+      - add_ssh_keys:
+          fingerprints:
+            - "13:1d:dd:c2:44:52:ea:22:c2:59:61:79:af:00:27:08"
+      # attach workspace so that you have access to the previously generated inventory.txt from the deploy-infrastructure job.
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies - Ansible
+          command: |
+            sudo add-apt-repository ppa:ansible/ansible
+            sudo apt-get update
+            sudo apt install ansible
+            sudo ansible --version
+      - run: 
+          name: Installing tar gzip
+          command: |
+             yum install -y tar gzip
+      
+      - run:
+          name: Install dependencies - NPM
+          # your code here  -> https://docs.npmjs.com/cli/v6/commands/npm-install
+          command: |
+            cd frontend
+            sudo npm install
+      - run:
+          name: Install dependencies - Nodejs
+          # your code here  -> Refer to https://docs.aws.amazon.com/cli/v1/userguide/install-linux.html
+          command: |
+            cd frontend
+            sudo apt install nodejs       
+          # your code here
+      - run:
+          name: Deploy backend
+          # your code here
+          command: |
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            tar -C backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is -------"
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml
+
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}
+          cond: on_fail
+
+
 workflows:
   default:
     jobs:
@@ -233,4 +393,6 @@ workflows:
               only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]    
                     
